name: Autobahn JS CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'

    - name: Update apt cache
      run: sudo apt update

    - name: Install APT dependencies
      run: |
        sudo pip3 install --no-cache-dir -U scons boto taschenmesser
    - name: Install NPM dependencens
      run: |
        sudo npm install -g nodeunit
    - name: Run tests
      run: cd packages/autobahn && npm install && npm test
